// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerBuddy.Context;
using PowerBuddy.Data.Context;

namespace PowerBuddy.Context.Migrations
{
    [DbContext(typeof(PowerLiftingContext))]
    partial class PowerLiftingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IdentityUserRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IdentityUserToken");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdminApprover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ExerciseTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainExercise")
                        .HasColumnType("bit");

                    b.HasKey("ExerciseId");

                    b.HasAlternateKey("ExerciseName");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("ExerciseMuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseMuscleGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseMuscleGroupId");

                    b.ToTable("ExerciseMuscleGroup");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.ExerciseMuscleGroupAssoc", b =>
                {
                    b.Property<int>("ExerciseMuscleGroupAssocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseMuscleGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("ExerciseMuscleGroupAssocId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseMuscleGroupAssoc");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.ExerciseSport", b =>
                {
                    b.Property<int>("ExerciseSportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseSportStr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseSportId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseSport");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.ExerciseType", b =>
                {
                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ExerciseTypeId");

                    b.HasAlternateKey("ExerciseTypeName");

                    b.ToTable("ExerciseType");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.FriendRequest", b =>
                {
                    b.Property<int>("FriendRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("HasAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("UserFromId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserToId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FriendRequestId");

                    b.HasIndex("UserFromId")
                        .IsUnique()
                        .HasFilter("[UserFromId] IS NOT NULL");

                    b.HasIndex("UserToId")
                        .IsUnique()
                        .HasFilter("[UserToId] IS NOT NULL");

                    b.ToTable("FriendRequest");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.FriendsListAssoc", b =>
                {
                    b.Property<int>("FriendsListAssocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("OtherUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FriendsListAssocId");

                    b.ToTable("FriendsListAssoc");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.LiftingLevel", b =>
                {
                    b.Property<int>("LiftingLevelId")
                        .HasColumnType("int");

                    b.Property<string>("LiftingLevelStr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LiftingLevelId");

                    b.ToTable("LiftingLevel");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.LiftingStatAudit", b =>
                {
                    b.Property<int>("LiftingStatAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutLogRepSchemeId")
                        .HasColumnType("int");

                    b.Property<int>("RepRange")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LiftingStatAuditId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogRepSchemeId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("LiftingStatAudit");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.MemberStatus", b =>
                {
                    b.Property<int>("MemberStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MemberStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberStatusId");

                    b.ToTable("MemberStatus");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NotificationText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.NotificationInteraction", b =>
                {
                    b.Property<int>("NotificationInteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("HasRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationInteractionId");

                    b.ToTable("NotificationInteraction");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLog", b =>
                {
                    b.Property<int>("WorkoutLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CustomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfWeeks")
                        .HasColumnType("int");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit");

                    b.Property<int?>("TemplateWorkoutId")
                        .HasColumnType("int");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.HasKey("WorkoutLogId");

                    b.HasIndex("TemplateWorkoutId");

                    b.ToTable("WorkoutLog");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogDay", b =>
                {
                    b.Property<int>("WorkoutLogDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutLogWeekId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkoutLogDayId");

                    b.HasIndex("WorkoutLogWeekId");

                    b.ToTable("WorkoutLogDay");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogExercise", b =>
                {
                    b.Property<int>("WorkoutLogExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfSets")
                        .HasColumnType("int");

                    b.Property<bool?>("PersonalBest")
                        .HasColumnType("bit");

                    b.Property<int>("WorkoutLogDayId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutLogExerciseTonnageId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutTemplateId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutLogExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogDayId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutLogExercise");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogExerciseAudit", b =>
                {
                    b.Property<int>("WorkoutLogExerciseAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkoutLogExerciseAuditId");

                    b.ToTable("WorkoutLogExerciseAudit");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogExerciseTonnage", b =>
                {
                    b.Property<int>("WorkoutLogExerciseTonnageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExerciseTonnage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkoutLogExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkoutLogExerciseTonnageId");

                    b.HasIndex("WorkoutLogExerciseId")
                        .IsUnique();

                    b.ToTable("WorkoutLogExerciseTonnage");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogRepScheme", b =>
                {
                    b.Property<int>("WorkoutLogRepSchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("AMRAP")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LiftingStatAuditId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfReps")
                        .HasColumnType("int");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkoutLogExerciseId")
                        .HasColumnType("int");

                    b.Property<int?>("RepsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("SetNo")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightLifted")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WorkoutLogRepSchemeId");

                    b.HasIndex("WorkoutLogExerciseId");

                    b.ToTable("WorkoutLogRepScheme");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogWeek", b =>
                {
                    b.Property<int>("WorkoutLogWeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekNo")
                        .HasColumnType("int");

                    b.HasKey("WorkoutLogWeekId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("WorkoutLogWeek");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("QuoteCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuoteStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("QuoteId");

                    b.ToTable("Quote");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.RepSchemeType", b =>
                {
                    b.Property<int>("RepSchemeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("RepSchemeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RepSchemeTypeId");

                    b.ToTable("RepSchemeType");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateDay", b =>
                {
                    b.Property<int>("TemplateDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DayNo")
                        .HasColumnType("int");

                    b.Property<int>("TemplateWeekId")
                        .HasColumnType("int");

                    b.HasKey("TemplateDayId");

                    b.HasIndex("TemplateWeekId");

                    b.ToTable("TemplateDay");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateDifficulty", b =>
                {
                    b.Property<int>("TemplateDifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TemplateDifficultyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateDifficultyId");

                    b.ToTable("TemplateDifficulty");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateExercise", b =>
                {
                    b.Property<int>("TemplateExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BackOffSetFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("HasBackOffSets")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfSets")
                        .HasColumnType("int");

                    b.Property<string>("RepSchemeFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepSchemeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateDayId")
                        .HasColumnType("int");

                    b.HasKey("TemplateExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateDayId");

                    b.ToTable("TemplateExercise");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateExerciseCollection", b =>
                {
                    b.Property<int>("TemplateExerciseCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateWorkoutId")
                        .HasColumnType("int");

                    b.HasKey("TemplateExerciseCollectionId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateWorkoutId");

                    b.ToTable("TemplateExerciseCollection");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateWorkout", b =>
                {
                    b.Property<int>("TemplateWorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ActiveUsersCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfDaysPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("NoOfWeeks")
                        .HasColumnType("int");

                    b.Property<string>("TemplateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightProgressionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateWorkoutId");

                    b.ToTable("TemplateWorkout");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateWorkoutAudit", b =>
                {
                    b.Property<int>("TemplateWorkoutAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateWorkoutId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TemplateWorkoutAuditId");

                    b.HasIndex("TemplateWorkoutId");

                    b.HasIndex("UserId");

                    b.ToTable("TemplateWorkoutAudit");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateRepScheme", b =>
                {
                    b.Property<int>("TemplateRepSchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("AMRAP")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBackOffSet")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfReps")
                        .HasColumnType("int");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SetNo")
                        .HasColumnType("int");

                    b.Property<int>("TemplateExerciseId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightLifted")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TemplateRepSchemeId");

                    b.HasIndex("TemplateExerciseId");

                    b.ToTable("TemplateRepScheme");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateWeek", b =>
                {
                    b.Property<int>("TemplateWeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateWorkoutId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNo")
                        .HasColumnType("int");

                    b.HasKey("TemplateWeekId");

                    b.HasIndex("TemplateWorkoutId");

                    b.ToTable("TemplateWeek");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FirstVisit")
                        .HasColumnType("bit");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiftingStatId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MemberStatusId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasIndex("GenderId");

                    b.HasIndex("MemberStatusId");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.UserSetting", b =>
                {
                    b.Property<int>("UserSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("BodyWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LiftingLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("QuotesEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("UsingMetric")
                        .HasColumnType("bit");

                    b.HasKey("UserSettingId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("UserSetting");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutDay", b =>
                {
                    b.Property<int>("WorkoutDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeekNo")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutLogId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutDayId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("WorkoutDay");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutExercise", b =>
                {
                    b.Property<int>("WorkoutExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutDayId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutTemplateId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutExercise");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLog", b =>
                {
                    b.Property<int>("WorkoutLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CustomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfWeeks")
                        .HasColumnType("int");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit");

                    b.Property<int?>("TemplateWorkoutId")
                        .HasColumnType("int");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.HasKey("WorkoutLogId");

                    b.ToTable("WorkoutLog");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutSet", b =>
                {
                    b.Property<int>("WorkoutSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("AMRAP")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LiftingStatAuditId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfReps")
                        .HasColumnType("int");

                    b.Property<int?>("RepsCompleted")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightLifted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutSetId");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutSet");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutTemplate", b =>
                {
                    b.Property<int>("WorkoutTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkoutTemplateId");

                    b.ToTable("WorkoutTemplate");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.Exercise", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId");

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.ExerciseMuscleGroupAssoc", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.Exercise", null)
                        .WithMany("ExerciseMuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.ExerciseSport", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.Exercise", null)
                        .WithMany("ExerciseSports")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.FriendRequest", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.User", null)
                        .WithOne("FriendRequestFrom")
                        .HasForeignKey("PowerBuddy.Data.Entities.FriendRequest", "UserFromId");

                    b.HasOne("PowerBuddy.Data.Entities.User", null)
                        .WithOne("FriendRequestTo")
                        .HasForeignKey("PowerBuddy.Data.Entities.FriendRequest", "UserToId");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.LiftingLevel", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.UserSetting", null)
                        .WithOne("LiftingLevel")
                        .HasForeignKey("PowerBuddy.Data.Entities.LiftingLevel", "LiftingLevelId");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.LiftingStatAudit", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.Exercise", "Exercise")
                        .WithMany("LiftingStatAudit")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PowerBuddy.Data.Entities.WorkoutLogRepScheme", "WorkoutLogRepScheme")
                        .WithOne("LiftingStatAudit")
                        .HasForeignKey("PowerBuddy.Data.Entities.LiftingStatAudit", "WorkoutLogRepSchemeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PowerBuddy.Data.Entities.User", "User")
                        .WithMany("LiftingStatAudit")
                        .HasForeignKey("UserId");

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLogRepScheme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLog", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.TemplateWorkout", "TemplateWorkout")
                        .WithMany()
                        .HasForeignKey("TemplateWorkoutId");

                    b.Navigation("TemplateWorkout");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogDay", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.WorkoutLogWeek", null)
                        .WithMany("WorkoutLogDays")
                        .HasForeignKey("WorkoutLogWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogExercise", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerBuddy.Data.Entities.WorkoutLogDay", null)
                        .WithMany("WorkoutLogExercises")
                        .HasForeignKey("WorkoutLogDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerBuddy.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutTemplateId");

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogExerciseTonnage", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.WorkoutLogExercise", "WorkoutLogExercise")
                        .WithOne("WorkoutLogExerciseTonnage")
                        .HasForeignKey("PowerBuddy.Data.Entities.WorkoutLogExerciseTonnage", "WorkoutLogExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("WorkoutLogExercise");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogRepScheme", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.WorkoutLogExercise", null)
                        .WithMany("WorkoutLogRepSchemes")
                        .HasForeignKey("WorkoutLogExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogWeek", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.WorkoutLog", "WorkoutLog")
                        .WithMany("WorkoutLogWeeks")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateDay", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.TemplateWeek", null)
                        .WithMany("TemplateDays")
                        .HasForeignKey("TemplateWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateExercise", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerBuddy.Data.Entities.TemplateDay", null)
                        .WithMany("TemplateExercises")
                        .HasForeignKey("TemplateDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateExerciseCollection", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerBuddy.Data.Entities.TemplateWorkout", null)
                        .WithMany("TemplateExerciseCollection")
                        .HasForeignKey("TemplateWorkoutId");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateWorkoutAudit", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.TemplateWorkout", "TemplateWorkout")
                        .WithMany()
                        .HasForeignKey("TemplateWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerBuddy.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("TemplateWorkout");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateRepScheme", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.TemplateExercise", null)
                        .WithMany("TemplateRepSchemes")
                        .HasForeignKey("TemplateExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateWeek", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.TemplateWorkout", null)
                        .WithMany("TemplateWeeks")
                        .HasForeignKey("TemplateWorkoutId");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.User", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId");

                    b.HasOne("PowerBuddy.Data.Entities.MemberStatus", "MemberStatus")
                        .WithMany("Users")
                        .HasForeignKey("MemberStatusId");

                    b.Navigation("Gender");

                    b.Navigation("MemberStatus");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.UserSetting", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.User", null)
                        .WithOne("UserSetting")
                        .HasForeignKey("PowerBuddy.Data.Entities.UserSetting", "UserId");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutDay", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.WorkoutLog", null)
                        .WithMany("WorkoutDays")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.WorkoutDay", null)
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutSet", b =>
                {
                    b.HasOne("PowerBuddy.Data.Entities.WorkoutExercise", null)
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscleGroups");

                    b.Navigation("ExerciseSports");

                    b.Navigation("LiftingStatAudit");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.MemberStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLog", b =>
                {
                    b.Navigation("WorkoutLogWeeks");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogDay", b =>
                {
                    b.Navigation("WorkoutLogExercises");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogExercise", b =>
                {
                    b.Navigation("WorkoutLogExerciseTonnage");

                    b.Navigation("WorkoutLogRepSchemes");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogRepScheme", b =>
                {
                    b.Navigation("LiftingStatAudit");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLogWeek", b =>
                {
                    b.Navigation("WorkoutLogDays");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateDay", b =>
                {
                    b.Navigation("TemplateExercises");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateExercise", b =>
                {
                    b.Navigation("TemplateRepSchemes");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateWorkout", b =>
                {
                    b.Navigation("TemplateExerciseCollection");

                    b.Navigation("TemplateWeeks");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.TemplateWeek", b =>
                {
                    b.Navigation("TemplateDays");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.User", b =>
                {
                    b.Navigation("FriendRequestFrom");

                    b.Navigation("FriendRequestTo");

                    b.Navigation("LiftingStatAudit");

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.UserSetting", b =>
                {
                    b.Navigation("LiftingLevel");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutDay", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutExercise", b =>
                {
                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutLog", b =>
                {
                    b.Navigation("WorkoutDays");
                });

            modelBuilder.Entity("PowerBuddy.Data.Entities.WorkoutTemplate", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
